name: J2MC_Lulz
main: to.joe.j2mc.lulz.J2MC_Lulz
version: 0.0prealpha
website: http://forums.joe.to
author: J2 Minecraft Plugin Team
description: Joke module.
commands:
  afk:
    description: Kicks player for being afk
    usage: |
            /afk
  extme:
    description: Extinguish.
    usage: |
            /extme
  flex:
    description: Flex.
    usage: |
            /flex