name: Lulz
main: to.joe.j2mc.lulz.J2MC_Lulz
version: 1.0
website: http://forums.joe.to
author: J2 Minecraft Plugin Team
description: Joke module.
commands:
  afk:
    description: Go afk
    usage: /afk
  extme:
    description: Extinguish yourself
    usage: /extme
  flex:
    description: Flex.
    usage: /flex
permissions:
  j2mc.lulz.extinguish:
    description: gives access to /extme command
    default: false
  j2mc.lulz.flex:
    description: allows user to flex B)
